spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  kafka:
    bootstrap-servers: 10.17.14.94:9092
    topic:
      dev: dev.t
      partitioned: partitioned.t
security:
  basic:
    enabled: false