version: '2'
services:
  kafka:
    build:
      context: kafka_zk
      dockerfile: Dockerfile
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "dev.t:1:1, gt1:1:1, ht1:1:1, pt1:1:1, gout:1:1, pout:1:1, hout:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  root:
    build: .
    depends_on:
      - kafka

  discovery-service:
    build:
      context: eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - root

  config-server:
    build:
      context: config
      dockerfile: Dockerfile
    depends_on:
      - root
    ports:
      - 8888:8888

  consumer:
     build:
        context: consumer
        dockerfile: Dockerfile
     ports:
      - "8181:8181"
     depends_on:
          - root

  g1service:
       build:
          context: g1service
          dockerfile: Dockerfile
       ports:
        - "8191:8191"
       depends_on:
            - root

  p1service:
       build:
           context: p1service
           dockerfile: Dockerfile
       ports:
          - "8193:8193"
       depends_on:
              - root

  h1service:
       build:
            context: h1service
            dockerfile: Dockerfile
       ports:
          - "8192:8192"
       depends_on:
              - root

  producer:
    build:
      context: producer
      dockerfile: Dockerfile
    ports:
      - "8180:8180"
    depends_on:
          - root